---
- name: install yggdrasil packages
  opkg:
    name: yggdrasil-go
  tags: wrt_ygg_install

- name: directory for yggdrasil configs
  file:
    path: /opt/etc/yggdrasil
    state: directory
    mode: 0755
  tags: wrt_ygg_install

- name: create yggdrasil startup script
  copy:
    src: yggdrasil.rc.sh
    dest: /opt/etc/init.d/{{ ygg_initd }}
    mode: 0755
    force: true
  register: _ygg_startup_result
  tags: wrt_ygg_install


- name: pull yggdrasil config from master peer
  slurp:
    src: "/etc/yggdrasil/yggdrasil.{{ alias }}"
  become: true
  delegate_to: "{{ ygg_master_host }}"
  vars:
    alias: "{{ ygg_alias |d(inventory_hostname, true) }}"
  register: _ygg_config_data
  tags: wrt_ygg_config

- name: update yggdrasil config
  copy:
    dest: /opt/etc/yggdrasil/yggdrasil.conf
    content: "{{ _ygg_config_data.content |b64decode }}"
    mode: 0644
    force: true
  register: _ygg_config_result
  tags: wrt_ygg_config

- name: pull isolated yggdrasil config from master peer
  slurp:
    src: "/etc/yggdrasil/yggdrasil.{{ alias }}-isolate"
  become: true
  delegate_to: "{{ ygg_master_host }}"
  vars:
    alias: "{{ ygg_alias |d(inventory_hostname, true) }}"
  register: _ygg_config_data_isolate
  tags: wrt_ygg_config

- name: update isolated yggdrasil config
  copy:
    dest: /opt/etc/yggdrasil/yggdrasil.isolate
    content: "{{ _ygg_config_data_isolate.content |b64decode }}"
    mode: 0644
    force: true
  register: _ygg_config_result
  tags: wrt_ygg_config


- name: enable/restart wrt service yggdrasil
  openwrt_init2:
    name: "{{ ygg_initd }}"
    state: "{{ 'restarted' if changed else 'started' }}"
  vars:
    changed: "{{ startup_changed or config_changed }}"
    startup_changed: "{{ _ygg_startup_result |d({}) is changed }}"
    config_changed: "{{ _ygg_config_result |d({}) is changed }}"
  tags:
    - skip_ansible_lint
    - wrt_ygg_config


- name: directory for the list of internal hosts
  file:
    path: /opt/etc/net
    state: directory
    mode: 0755
  tags: wrt_ygg_firewall

- name: add yggdrasil hosts to the list of internal hosts
  template:
    src: int-hosts.yggdrasil.j2
    dest: /opt/etc/net/int-hosts.ygg
    mode: 0644
  notify: restart wrt service routing (yggdrasil)
  tags: wrt_ygg_firewall
...
